[features]
seeds = false
skip-lint = false

[programs.localnet]
calculatordapp = "64RvgDGkC42kFsW6vjyJQbcRCCcJviK9rfXqr3WQzw37"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/josephineliang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
